//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiggaTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NiggaTable()
        {
            this.UserNigga = new HashSet<UserNigga>();
        }
    
        public int ID { get; set; }
        public string SIze { get; set; }
        public string Name { get; set; }
        public int Article { get; set; }
        public string Speed { get; set; }
        public int CountryCode { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNigga> UserNigga { get; set; }
    }
}
